// generated 2020-12-30 13:43:57.2742522 +0900 KST m=+0.007994601
Map<String, Map<String, String>> localizedValues = {
  'en_US': {
    'about_this_app': 'About this app',
    'are_you_sure_you_want_to_clear_history':
        'Are you sure you want to clear history?',
    'are_you_sure_you_want_to_exit': 'Are you sure you want to exit?',
    'averate_abbr': 'AVG',
    'cancel': 'Cancel',
    'close': 'Close',
    'copy': 'Copy',
    'dark_mode': 'Dark Mode',
    'error': 'Error',
    'failed_to_load': 'Failed to load.',
    'flashlight': 'Flashlight',
    'google_url': 'www.google.com',
    'information': 'Information',
    'install_date': 'Install Date',
    'keep_the_device_awake': 'Keep the device awake',
    'keep_the_screen_on': 'Keep the screen on',
    'maximum_abbr': 'MAX',
    'minimum_abbr': 'MIN',
    'more_apps': 'More apps',
    'off': 'Off',
    'ok': 'Ok',
    'on': 'On',
    'open': 'Open',
    'open_settings': 'Open Settings',
    'open_website_automatically': 'Open website automatically',
    'pause': 'Pause',
    'permission_denied': 'Permission denied',
    'please_allow_permission_in_settings':
        'Necessary permissions are denied. Please allow in Settings.',
    'purchase_history': 'Purchase History',
    'rate_review': 'Rate 5 stars',
    'remove': 'Remove',
    'resume': 'Resume',
    'reset': 'Reset',
    'scan_history': 'Scan History',
    'scan_result': 'Scan Result',
    'screenshot': 'Screenshot',
    'screenshot_saved': 'Screenshot saved',
    'search': 'Search',
    'settings': 'Settings',
    'share': 'Share',
    'share_app': 'Share App',
    'show_example_noise_level': 'Show the example noise level',
    'statistics': 'Statistics',
    'updated_date': 'Updated date',
    'vibrate': 'Vibrate',
    'view code': 'View code',
    'grant_permission': 'Grant Permission',
    'loading': 'Loading...',
    'no_camera_available': 'No Camera Available',
  },
  'ko_KR': {
    'about_this_app': '앱 정보',
    'are_you_sure_you_want_to_clear_history': '정말 모든 기록을 삭제하시겠습니까?',
    'are_you_sure_you_want_to_exit': '종료하시겠습니까?',
    'averate_abbr': '평균',
    'cancel': '취소',
    'close': '닫기',
    'copy': '복사',
    'dark_mode': '다크 모드',
    'error': '오류',
    'failed_to_load': '불러오기에 실패했습니다.',
    'flashlight': '손전등',
    'google_url': 'www.google.co.kr',
    'information': '정보',
    'install_date': '설치일자',
    'keep_the_device_awake': '기기를 켜진 상태로 유지',
    'keep_the_screen_on': '화면을 켜진 상태로 유지',
    'maximum_abbr': '최대',
    'minimum_abbr': '최소',
    'more_apps': '다른 앱 보기',
    'off': '끔',
    'ok': '확인',
    'on': '켬',
    'open': '열기',
    'open_settings': '설정 열기',
    'open_website_automatically': '웹 사이트 자동으로 열기',
    'pause': '일시정지',
    'permission_denied': '권한 없음',
    'please_allow_permission_in_settings':
        '권한이 없어 해당 기능을 사용할 수 없습니다. 앱 설정에서 권한을 허용해주세요.',
    'purchase_history': '구매내역',
    'rate_review': '별점주기',
    'remove': '삭제',
    'resume': '재시작',
    'reset': '초기화',
    'scan_history': '스캔 내역',
    'scan_result': '스캔 결과',
    'screenshot': '화면캡쳐',
    'screenshot_saved': '화면캡쳐 성공',
    'search': '검색',
    'settings': '설정',
    'share': '공유',
    'share_app': '앱 공유하기',
    'show_example_noise_level': '소음수준 정보 표시',
    'statistics': '통계',
    'updated_date': '업데이트 일자',
    'vibrate': '진동',
    'view code': '코드 보기',
    'grant_permission': '권한 허용하기',
    'loading': '준비중입니다...',
    'no_camera_available': '카메라를 찾을 수 없습니다',
  },
  'pl_PL': {
    'about_this_app': 'Informacje o aplikacji',
    'are_you_sure_you_want_to_clear_history':
        'Czy na pewno chcesz usunąć wszystkie przedmioty?',
    'are_you_sure_you_want_to_exit': 'Are you sure you want to exit?',
    'averate_abbr': 'AVG',
    'cancel': 'Anuluj',
    'close': 'zamknij',
    'copy': 'Kopiuj',
    'dark_mode': 'tryb ciemny',
    'error': 'Błąd',
    'failed_to_load': 'Failed to load.',
    'flashlight': 'Latarka',
    'google_url': 'www.google.pl',
    'information': 'Informacje',
    'install_date': 'Install Date',
    'keep_the_device_awake': 'Keep the device awake',
    'keep_the_screen_on': 'Keep the screen on',
    'maximum_abbr': 'MAX',
    'minimum_abbr': 'MIN',
    'more_apps': 'Więcej aplikacji',
    'off': 'Off',
    'ok': 'Ok',
    'on': 'On',
    'open': 'Otwarte',
    'open_settings': 'Otwórz ustawienia',
    'open_website_automatically': 'Open website automatically',
    'pause': 'Pauza',
    'permission_denied': 'Brak uprawnień',
    'please_allow_permission_in_settings':
        'Necessary permissions are denied. Please allow in Settings.',
    'purchase_history': 'Historia zakupów',
    'rate_review': 'Rate 5 stars',
    'remove': 'Usuń',
    'resume': 'Resume',
    'reset': 'Resetuj',
    'scan_history': 'Scan Historia',
    'scan_result': 'Scan Rezultat',
    'screenshot': 'Zrzut ekranu',
    'screenshot_saved': 'Zrzut ekranu saved',
    'search': 'szukanie',
    'settings': 'Ustawienia',
    'share': 'Dzielić',
    'share_app': 'Share App',
    'show_example_noise_level': 'Show the example noise level',
    'statistics': 'Statystyka',
    'updated_date': 'Updated date',
    'vibrate': 'Vibrate',
    'view code': 'Zobacz kod',
    'grant_permission': 'Grant Permission',
    'loading': 'Ładuję...',
    'no_camera_available': 'Brak dostępnej kamery',
  },
};
